/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.alia4j.language.textadventure.resource.textadventure.grammar;

public class TextadventureGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static TextadventureGrammarInformationProvider INSTANCE = new TextadventureGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_0_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWorld().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WORLD__TILES), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_0_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWorld().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WORLD__ITEMS), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getItem(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_0_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWorld().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WORLD__PERSONS), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getPerson(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_0_0_0_0, TEXTADVENTURE_0_0_0_1, TEXTADVENTURE_0_0_0_2);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_0_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWorld(), TEXTADVENTURE_0_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("tile", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_1_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.TILE__ID), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("{", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("x", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_4 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("=", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_1_0_0_5 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.TILE__X), "INTEGER", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_6 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("y", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_7 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("=", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_1_0_0_8 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.TILE__Y), "INTEGER", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_9 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("description", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_10 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("=", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_1_0_0_11 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.TILE__DESCRIPTION), "QUOTED_34_34", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_1_0_0_12 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("}", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_1_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_1_0_0_0, TEXTADVENTURE_1_0_0_1, TEXTADVENTURE_1_0_0_2, TEXTADVENTURE_1_0_0_3, TEXTADVENTURE_1_0_0_4, TEXTADVENTURE_1_0_0_5, TEXTADVENTURE_1_0_0_6, TEXTADVENTURE_1_0_0_7, TEXTADVENTURE_1_0_0_8, TEXTADVENTURE_1_0_0_9, TEXTADVENTURE_1_0_0_10, TEXTADVENTURE_1_0_0_11, TEXTADVENTURE_1_0_0_12);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_1_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_1_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getTile(), TEXTADVENTURE_1_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_2_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("item", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_2_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getItem().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.ITEM__NAME), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_2_0_0_2_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("@", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_2_0_0_2_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getItem().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.ITEM__LOCATION), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_2_0_0_2_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0_2_0_0_0, TEXTADVENTURE_2_0_0_2_0_0_1);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_2_0_0_2_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0_2_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCompound TEXTADVENTURE_2_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCompound(TEXTADVENTURE_2_0_0_2_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.QUESTIONMARK);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_2_0_0_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("{", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_2_0_0_4_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getItem().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.ITEM__EFFECTS), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getEffect(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_2_0_0_4_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0_4_0_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_2_0_0_4_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0_4_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCompound TEXTADVENTURE_2_0_0_4 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCompound(TEXTADVENTURE_2_0_0_4_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.STAR);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_2_0_0_5 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("}", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_2_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0_0, TEXTADVENTURE_2_0_0_1, TEXTADVENTURE_2_0_0_2, TEXTADVENTURE_2_0_0_3, TEXTADVENTURE_2_0_0_4, TEXTADVENTURE_2_0_0_5);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_2_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_2_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getItem(), TEXTADVENTURE_2_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal TEXTADVENTURE_3_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getBinding().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.BINDING__PARTICIPANT), new String[] {"ON", "on", }, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_3_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getBinding().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.BINDING__ID), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_3_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_3_0_0_0, TEXTADVENTURE_3_0_0_1);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_3_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_3_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getBinding(), TEXTADVENTURE_3_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_4_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("while", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal TEXTADVENTURE_4_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWhileEffect().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WHILE_EFFECT__CONDITION), new String[] {"USED", "used", }, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_4_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWhileEffect().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WHILE_EFFECT__BINDING), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getBinding(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_4_0_0_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("{", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_4_0_0_4 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWhileEffect().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.WHILE_EFFECT__ACTION), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getAction(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_4_0_0_5 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("}", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_4_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_4_0_0_0, TEXTADVENTURE_4_0_0_1, TEXTADVENTURE_4_0_0_2, TEXTADVENTURE_4_0_0_3, TEXTADVENTURE_4_0_0_4, TEXTADVENTURE_4_0_0_5);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_4_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_4_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_4 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getWhileEffect(), TEXTADVENTURE_4_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_5_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("remove", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_5_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getRemoveAction().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.REMOVE_ACTION__WHAT), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_5_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("from", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_5_0_0_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getRemoveAction().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.REMOVE_ACTION__FROM), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getList(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_5_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_5_0_0_0, TEXTADVENTURE_5_0_0_1, TEXTADVENTURE_5_0_0_2, TEXTADVENTURE_5_0_0_3);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_5_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_5_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_5 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getRemoveAction(), TEXTADVENTURE_5_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal TEXTADVENTURE_6_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getList().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.LIST__POSITION), new String[] {"RESULT", "result", }, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal TEXTADVENTURE_6_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getList().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.LIST__TARGET), new String[] {"TILE", "Tile", }, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal TEXTADVENTURE_6_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getList().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.LIST__PROPERTY), new String[] {"PERSONS", "Persons", "ITEMS", "Items", }, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_6_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_6_0_0_0, TEXTADVENTURE_6_0_0_1, TEXTADVENTURE_6_0_0_2);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_6_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_6_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_6 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getList(), TEXTADVENTURE_6_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_7_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("person", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_7_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getPerson().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.PERSON__NAME), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_7_0_0_2 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("@", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_7_0_0_3 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getPerson().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.PERSON__LOCATION), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_7_0_0_4 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("{", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment TEXTADVENTURE_7_0_0_5 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureContainment(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getPerson().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.PERSON__ABILITIES), org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getAbility(), }, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_7_0_0_6 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("}", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_7_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_7_0_0_0, TEXTADVENTURE_7_0_0_1, TEXTADVENTURE_7_0_0_2, TEXTADVENTURE_7_0_0_3, TEXTADVENTURE_7_0_0_4, TEXTADVENTURE_7_0_0_5, TEXTADVENTURE_7_0_0_6);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_7_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_7_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_7 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getPerson(), TEXTADVENTURE_7_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword TEXTADVENTURE_8_0_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword("ignore", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder TEXTADVENTURE_8_0_0_1 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventurePlaceholder(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getIgnoreItemAbility().getEStructuralFeature(org.alia4j.language.textadventure.TextadventurePackage.IGNORE_ITEM_ABILITY__IGNORED_ITEM), "TEXT", org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, 0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence TEXTADVENTURE_8_0_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSequence(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_8_0_0_0, TEXTADVENTURE_8_0_0_1);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice TEXTADVENTURE_8_0 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureChoice(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE, TEXTADVENTURE_8_0_0);
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule TEXTADVENTURE_8 = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule(org.alia4j.language.textadventure.TextadventurePackage.eINSTANCE.getIgnoreItemAbility(), TEXTADVENTURE_8_0, org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureCardinality.ONE);
	
	public static String getSyntaxElementID(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSyntaxElement) org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule[] RULES = new org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule[] {
		TEXTADVENTURE_0,
		TEXTADVENTURE_1,
		TEXTADVENTURE_2,
		TEXTADVENTURE_3,
		TEXTADVENTURE_4,
		TEXTADVENTURE_5,
		TEXTADVENTURE_6,
		TEXTADVENTURE_7,
		TEXTADVENTURE_8,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword) {
			keywords.add(((org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureKeyword) element).getValue());
		} else if (element instanceof org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureBooleanTerminal) {
			keywords.add(((org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureBooleanTerminal) element).getTrueLiteral());
			keywords.add(((org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal) {
			org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal terminal = (org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (org.alia4j.language.textadventure.resource.textadventure.grammar.TextadventureSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
